@url = http://localhost:3000/local/api

###
# @name getAccounts
GET {{url}}/get?id=83a6c9aa-828f-4df4-9583-3862a1327a80

###
# @name createAccount
POST {{url}}/post
Content-Type: application/json

{
  "name": "Nome da Conta",
  "value": 42
}

###
# @name deleteAccount
DELETE {{url}}/delete?id=123