@url = http://localhost:3000/local/api

###
# @name getAccount
GET {{url}}/get?id=89cb6b37-43fd-4107-9ad4-0ff5bf1c933f

###
# @name createAccount
POST {{url}}/post
Content-Type: application/json

{
  "name": "Amazon Prime",
  "value": 15
}

###
# @name updateAccount
PUT {{url}}/put
Content-Type: application/json

{
  "id": "89cb6b37-43fd-4107-9ad4-0ff5bf1c933f",
  "name": "Amazon Prime",
  "value": 21
}

###
# @name deleteAccount
DELETE {{url}}/delete?id=89cb6b37-43fd-4107-9ad4-0ff5bf1c933f