service: financa-organizada-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: "local"
  region: "us-east-1"
  memorySize: 128
  timeout: 3

custom:
  serverless-offline-watcher:
    - path: src/**/*.ts
      command: echo "code was modified!"
  localstack:
    stages:
      - local
    host: http://financa-organizada-localstack
    edgePort: 4566
    networkName: financa-organizada-network

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-offline-watcher
  - serverless-localstack

functions:
  getAccount:
    handler: src/handler.getAccount
    description: function description
    events:
      - http:
          path: /api/get
          method: get
          cors: true
  getAllAccounts:
    handler: src/handler.getAllAccounts
    description: function description
    events:
      - http:
          path: /api/getAll
          method: get
          cors: true
  postAccount:
    handler: src/handler.postAccount
    description: function description
    events:
      - http:
          path: /api/post
          method: post
          cors: true
  putAccount:
    handler: src/handler.putAccount
    description: function description
    events:
      - http:
          path: /api/put
          method: put
          cors: true
  deleteAccount:
    handler: src/handler.deleteAccount
    description: function description
    events:
      - http:
          path: /api/delete
          method: delete
          cors: true

resources:
  Resources:
    AccountsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: AccountsTable
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
